### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by patrek** [ksokol/carldav#11]
Quick question: where do you intend to go for persistence? Still use hibernate, switch to jpa or other?

**Comment by ksokol** [comment]
I want to switch to Spring Data JPA or at least just plain JPA in the future. Before that, I'll have to refactor a lot of code. Righ now, I can not say long does it take to switch to JPA.

**Comment by patrek** [comment]
Thanks. I was not asking for a timeline, just a general direction.

**Comment by ksokol** [comment]
FYI: Finally, I managed to replace Hibernate with Spring Data JPA. Right now I'm testing it on my on server with my devices for bugs.
